#CFLAGS=-std=gnu99 -Wall -Wextra -Werror -pedantic
CFLAGS=-std=gnu99 -Wall -Wextra
#PARTS=main.o
PARTS=main.c

proj2: ${PARTS}
	gcc ${CFLAGS} ${PARTS} -o proj2

#main.o: main.c
#	gcc ${CFLAGS} main.c -o main.o
