#!/bin/bash
i=$1
awk="{ \
        flag = 0; \
        for (i = 1; i <= NF; i++) { \
                print \$i; \
                if ("\$i" ~ pattern) { \
                        flag = 1 \ 
                } \
                print flag; \
        } \
        if (flag == 0) { \
                print \$0 \
        } \
}"
awks="{ \
	flag = 0; \
        for (i = 1; i <= NF; i++) { \
                if ("\$i" ~ pattern) { \
                        flag = 1 \ 
                } \
        } \
        if (flag == 0) { \
                print \$0 \
        } \
}"
awkt="{i=2; print \$i}"
#echo $awk
pwd | awk -F/ -v pattern="$i" "$awks"
#$awks
