#!/bin/bash

POSIXLY_CORRECT=yes

function help {
	echo "Usage: ./dirgraph [-i FILE_ERE] [-n] [DIR]" >&2
	return 1
}

# COMMAND LINE PARSE
dir="."
i=false
n=false

setopt=":i:n"
while getopts "$setopt" opt; do
	
	if [[ $OPTARG =~ ^-.* ]]; then		#Required argument testing (! -i -n)
		help
        	exit 1
     	fi

	case $opt in
		i) i="$OPTARG";;
		n) n=true;;
		?) help; exit 1;;
	esac
done

shift $(($OPTIND - 1))		#On $1 shift dir path

if [ -n "$1" -a -e "$1" -a $# -eq 1 ]; then
	dir=$1
elif [ $# -gt 1 -o -n "$1" -a ! -e "$1" ]; then
	help
	exit 1
fi
echo "$i $n $dir $#"

